name: Storybook Deploy

on:
  push:
    branches:
      - hyeryongchoi

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Use repository source
        uses: actions/checkout@v3

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache Yarn global cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Yarn project cache
        uses: actions/cache@v2
        with:
          path: ./frontend/.yarn/cache
          key: ${{ runner.os }}-yarn-project-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-project-

      - name: Clear Yarn cache
        run: |
          rm -rf .yarn/cache

      - name: Install dependencies
        run: yarn install

      - name: Set PUBLIC_URL
        run: |
          PUBLIC_URL=$(echo $GITHUB_REPOSITORY | sed -r 's/^.+\/(.+)$/\/\1\//')
          echo PUBLIC_URL=$PUBLIC_URL > .env

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy To 'storybook-deploy' Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: storybook-deploy
          publish_dir: ./storybook-static
